import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Check from "@/components/check";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <div>
      <Check/>
      {children}
    </div>

  );
}
